apply plugin: 'org.springframework.boot'

dependencies {
	// 도메인 모듈 의존성
	implementation project(':module-application')
	implementation project(':module-common')
	
	// Spring Web
	implementation 'org.springframework.boot:spring-boot-starter-web'
	
	// Validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	
	// API 문서화 (Swagger/OpenAPI)
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'

	// Spring Boot 애플리케이션 실행을 위한 기본 의존성
	implementation 'org.springframework.boot:spring-boot-starter'
	
	// 설정 프로퍼티
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}